### PR TITLE
Updated parameters and implemented log rotation of dynamodb

### PR DESCRIPTION
**Pull request by taherbohari**
Implemented following features :
- corrected some tasks
- defined parameters for installation dirs, log files etc
- implemented log rotation

### CODE REVIEW

**Comment by MiLk** [comment]
Thank you for your PR.

@tokyowizard Could you take care of that one?

**Review by tokyowizard — APPROVED** [review]
👍 LGTM

**Comment by MiLk** [comment]
@christopherobin Should I do a release now or do you think #3 will come quickly?

**Comment by christopherobin** [comment]
I'll try to take care of #3 by the end of the week

**Pull request merged**
